interview_EF/Controllers/AuthorController.cs
using DataAccess.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Model.Models;
using System.Threading.Tasks;

namespace interview_EF.Controllers
{
    public class AuthorController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AuthorController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            List<Author> Author = _db.Authors.ToList();

            return View(Author);
        }
        public IActionResult Upsert(int? id)
        {
            Author obj = new();
            if(id==null ||id==0)
            {
                return View(obj);
            }
            obj = _db.Authors.FirstOrDefault(u => u.Author_Id == id);
            if (obj == null)
                return NotFound();

            return View(obj);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Author obj)
        {
            if (ModelState.IsValid)
            {
                if (obj.Author_Id == 0)
                {
                    await _db.Authors.AddAsync(obj);
                }
                else
                {
                    _db.Authors.Update(obj);
                }
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(obj);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            Author obj = new();
            obj = await _db.Authors.FirstOrDefaultAsync(u => u.Author_Id == id);
            if(obj==null)
            {
                return NotFound();
            }
            _db.Authors.Remove(obj);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

interview_EF/Controllers/BookController.cs
using DataAccess.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Model.Models;
using Model.ViewModel;
using System.Threading.Tasks;

namespace interview_EF.Controllers
{
    public class BookController : Controller
    {
        private readonly ApplicationDbContext _db;
        public BookController(ApplicationDbContext db)
        {
            _db = db;
        }
        // multiple time hit db
        //public IActionResult Index()
        //{
        //   // List<Book> objList = _db.Books.Include(b => b.Publisher).ToList();
        //   List<Book> objList = _db.Books.ToList();
        //    foreach (var obj in objList)
        //    {
        //    //    //less effeicient
        //    //    //obj.Publisher = _db.Publishers.Find(obj.Publisher_Id);
        //    //    //more effeicient
        //          _db.Entry(obj).Reference(i=>i.Publisher).Load();
        //          _db.Entry(obj).Collection(i=>i.Authors).Load();
        //        foreach (var bookAuth in obj.Authors)
        //        {
        //            _db.Entry(bookAuth).Reference(i => i.Author).Load();
        //        }
        //    }
        //    return View(objList);
        //}
        public IActionResult Index()
        {
             List<Book> objList = _db.Books.Include(b => b.Publisher).Include(u=>u.Authors).ThenInclude(i=>i.Author).ToList();

            //List<Book> objList = _db.Books.ToList();
            //foreach (var obj in objList)
            //{
            //    //    //less effeicient
            //    //    //obj.Publisher = _db.Publishers.Find(obj.Publisher_Id);
            //    //    //more effeicient
            //    _db.Entry(obj).Reference(i => i.Publisher).Load();
            //    _db.Entry(obj).Collection(i => i.Authors).Load();
            //    foreach (var bookAuth in obj.Authors)
            //    {
            //        _db.Entry(bookAuth).Reference(i => i.Author).Load();
            //    }
            //}
            return View(objList);
        }
        public IActionResult Upsert(int? id)
        {
            BookVM obj = new();
            obj.PublisherList = _db.Publishers.Select(i => new SelectListItem
            {
                Text= i.Name,
                Value=i.Publisher_Id.ToString()
            });
            if (id == null || id == 0)
            {
                return View(obj);
            }
            //edit
            obj.Book = _db.Books.FirstOrDefault(u => u.IDBook == id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(BookVM obj)
        {
            
           
                if (obj.Book.IDBook == 0)
                {
                    await _db.Books.AddAsync(obj.Book);
                }
                else
                {
                    _db.Books.Update(obj.Book);
                }
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            
           // return View(obj);
        }
        public IActionResult Details(int? id)
        {
            //BookVM obj = new();

            BookDetail obj = new();

            if (id == null || id == 0)
            {
                return NotFound();
            }
            //edit
            //obj.Book = _db.Books.FirstOrDefault(u => u.IDBook == id);
            obj = _db.BookDetails.Include(o=>o.Book).FirstOrDefault(u => u.IDBook == id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(BookDetail obj)
        {

           
            if (obj.BookDetail_Id == 0)
            {
                await _db.BookDetails.AddAsync(obj);
            }
            else
            {
                _db.BookDetails.Update(obj);
            }
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");

            // return View(obj);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            Book obj = new();
            //edit
            obj = _db.Books.FirstOrDefault(u => u.IDBook == id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Books.Remove(obj);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public IActionResult ManageAuthors(int id)
        {
            BookAuthorVM obj = new()
            {
                BookAuthorList = _db.BookAuthorMaps.Include(u=>u.Author).Include(u=>u.Book)
                .Where(u => u.IDBook == id).ToList(),
                BookAuthor =new()
                {
                    IDBook=id
                },
                Book=_db.Books.FirstOrDefault(u => u.IDBook == id), 
            };
            List<int> tempListAssignAuthor=obj.BookAuthorList.Select(u => u.Author_Id).ToList();
            //not IN Clause
            //get all the authors whos id is not in tempListOfAssignedAuthor 
            var tempList = _db.Authors.Where(u => !tempListAssignAuthor.Contains(u.Author_Id)).ToList();
            obj.AuthorList = tempList.Select(i => new SelectListItem
            {
                Text=i.FullName,
                Value=i.Author_Id.ToString()
            });
            return View(obj);
        }
        [HttpPost]
        public IActionResult ManageAuthors(BookAuthorVM bookAuthorVM)
        {
            if(bookAuthorVM.BookAuthor.IDBook!=0 && bookAuthorVM.BookAuthor.Author_Id!=0)
            {
                _db.BookAuthorMaps.Add(bookAuthorVM.BookAuthor);
                _db.SaveChanges();
            }
            return RedirectToAction(nameof(ManageAuthors),new { @id= bookAuthorVM.BookAuthor.IDBook});
        }
        [HttpPost]
        public IActionResult RemoveAuthors(int authorId, BookAuthorVM bookAuthorVM)
        {
            int bookID=bookAuthorVM.Book.IDBook;
            BookAuthorMap bookAuthorMap = _db.BookAuthorMaps.FirstOrDefault(u => u.Author_Id ==authorId && u.IDBook == bookID);

           
                _db.BookAuthorMaps.Remove(bookAuthorMap);
                _db.SaveChanges();
            
            return RedirectToAction(nameof(ManageAuthors), new { @id = bookID });
        }
    }
}

interview_EF/Controllers/CategoryController.cs
using DataAccess.Data;
using Microsoft.AspNetCore.Mvc;
using Model.Models;
using System.Threading.Tasks;

namespace interview_EF.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            List<Category> objList = _db.Categories.ToList();
            return View(objList);
        }
        public IActionResult Upsert(int? id)
        {
            Category obj = new();
            if(id==null || id==0)
            {
                return View(obj);
            }
            //edit
            obj = _db.Categories.FirstOrDefault(u => u.CategoryId == id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< IActionResult >Upsert(Category obj)
        {
            if(ModelState.IsValid)
            {
                if(obj.CategoryId==0)
                {
                    await _db.Categories.AddAsync(obj);
                }
                else
                {
                     _db.Categories.Update(obj);
                }
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            Category obj = new();
            //edit
            obj = _db.Categories.FirstOrDefault(u => u.CategoryId == id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Categories.Remove(obj);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public IActionResult CreateMultiple2()
        {
            List<Category> Category = new();
            for (int i = 0; i < 2; i++)
            {
                Category.Add(new Category
                {
                    CategoryName = Guid.NewGuid().ToString()
                });
            }
            _db.Categories.AddRange(Category);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult CreateMultiple5()
        {
            List<Category> Category = new();
            for (int i = 0; i < 5; i++)
            {
                Category.Add(new Category
                {
                    CategoryName = Guid.NewGuid().ToString()
                });
            }
            _db.Categories.AddRange(Category);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult RemoveMultiple2()
        {
            List<Category> Category = _db.Categories.OrderByDescending(u=>u.CategoryId).Take(2).ToList();
            
            _db.Categories.RemoveRange(Category);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult RemoveMultiple5()
        {
            List<Category> Category =_db.Categories.OrderByDescending(u=>u.CategoryId).Take(5).ToList();
            _db.Categories.RemoveRange(Category);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

interview_EF/Controllers/PublisherController.cs
using DataAccess.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Model.Models;
using System.Threading.Tasks;

namespace interview_EF.Controllers
{
    public class PublisherController : Controller
    {
        private readonly ApplicationDbContext _db;
        public PublisherController(ApplicationDbContext db)
        {
             _db = db;
        }

        public IActionResult Index()
        {
            List<Publisher> Publisher = _db.Publishers.ToList();
            return View(Publisher);
        }
        public IActionResult Upsert(int? id)
        {
            Publisher obj = new();
            if(id== null || id==0)
            {
                return View(obj);
            }
            obj= _db.Publishers.FirstOrDefault(u=>u.Publisher_Id==id);
            if(obj== null)
            {
                return NotFound();
            }
            return View(obj);
            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< IActionResult >Upsert(Publisher obj)
        {
            if(ModelState.IsValid)
            {
                if(obj.Publisher_Id==0)
                {
                    await _db.Publishers.AddAsync(obj);
                }
                else
                {
                    _db.Publishers.Update(obj);
                }
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(obj);
        }
        public async Task<IActionResult> Delete(int? id)
        {
           Publisher obj=new();

            obj = await _db.Publishers.FirstOrDefaultAsync(u => u.Publisher_Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Publishers.Remove(obj);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
       
    }
}

interview_EF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - interview_EF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/interview_EF.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" integrity="sha512-ELV+xyi8IhEApPS/pSj66+Jiw+sOT1Mqkzlh8ExXihe4zfqbWkxPRi8wptXIO9g73FSlhmquFlUOuMSoXz5IRw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">interview_EF</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publisher" asp-action="Index">Publisher</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Author</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Book</a>
                        </li>
                        </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - interview_EF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js" integrity="sha512-57oZ/vW8ANMjR/KQ6Be9v/+/h6bq9/l3f0Oc7vn6qMqyhvPd1cvKBRWWpzu0QoneImqr2SkmO4MSqU+RpHom3Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>